# Generated by Django 4.2.7 on 2023-12-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('Director', models.CharField(max_length=50)),
            ],
        ),
    ]
