# Generated by Django 4.2.7 on 2023-11-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=200)),
                ('t', models.CharField(max_length=200)),
                ('r', models.CharField(max_length=200)),
                ('d', models.CharField(max_length=200)),
            ],
        ),
    ]
